/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techtonic;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.Vector;
import javax.swing.BorderFactory;
//import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jwitsml.WitsmlLog;
import org.jwitsml.WitsmlLogCurve;
import org.jwitsml.WitsmlWell;
import org.jwitsml.WitsmlWellbore;
import java.net.MalformedURLException;

/**
 *
 * @author 1412625
 */
public class Techtonic extends javax.swing.JFrame {

    /**
     * Creates new form Techtonic
     */
    public Techtonic() {
        initComponents();
        loadDisplayScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBarPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        toolBarPanel = new javax.swing.JPanel();
        operatorPanel = new javax.swing.JPanel();
        combOperator = new javax.swing.JComboBox<>();
        lblOperators = new javax.swing.JLabel();
        jspWell = new javax.swing.JScrollPane();
        btnWellPanel = new javax.swing.JPanel();
        lblOperatorName = new javax.swing.JLabel();
        jspWellBore = new javax.swing.JScrollPane();
        wellBorePanel = new javax.swing.JPanel();
        jspProperty = new javax.swing.JScrollPane();
        tblProperty = new javax.swing.JTable();
        displayAreaPanel = new javax.swing.JPanel();
        menBarTectTonic = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiNew = new javax.swing.JMenuItem();
        jmiLoad = new javax.swing.JMenuItem();
        jmiSave = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Techtonic");
        setName("TechTonic"); // NOI18N
        setPreferredSize(new java.awt.Dimension(100, 200));
        setSize(new java.awt.Dimension(1000, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBarPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon("H:\\NetBeansProjects\\TeckhTonic\\TeckTonic Logo.jpg")); // NOI18N

        javax.swing.GroupLayout titleBarPanelLayout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(titleBarPanelLayout);
        titleBarPanelLayout.setHorizontalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(1142, Short.MAX_VALUE))
        );
        titleBarPanelLayout.setVerticalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        getContentPane().add(titleBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1280, -1));

        toolBarPanel.setPreferredSize(new java.awt.Dimension(100, 65));

        javax.swing.GroupLayout toolBarPanelLayout = new javax.swing.GroupLayout(toolBarPanel);
        toolBarPanel.setLayout(toolBarPanelLayout);
        toolBarPanelLayout.setHorizontalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        toolBarPanelLayout.setVerticalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        getContentPane().add(toolBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, 1110, -1));

        operatorPanel.setBackground(new java.awt.Color(0, 0, 0));

        combOperator.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        combOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combOperatorActionPerformed(evt);
            }
        });

        lblOperators.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblOperators.setForeground(new java.awt.Color(0, 153, 153));
        lblOperators.setText("Operators");

        javax.swing.GroupLayout operatorPanelLayout = new javax.swing.GroupLayout(operatorPanel);
        operatorPanel.setLayout(operatorPanelLayout);
        operatorPanelLayout.setHorizontalGroup(
            operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperators)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operatorPanelLayout.setVerticalGroup(
            operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combOperator, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblOperators))
                .addContainerGap())
        );

        getContentPane().add(operatorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 390, -1));

        jspWell.setBorder(null);
        jspWell.setPreferredSize(new java.awt.Dimension(1173, 2263));

        btnWellPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(0), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnWellPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout btnWellPanelLayout = new javax.swing.GroupLayout(btnWellPanel);
        btnWellPanel.setLayout(btnWellPanelLayout);
        btnWellPanelLayout.setHorizontalGroup(
            btnWellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        btnWellPanelLayout.setVerticalGroup(
            btnWellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jspWell.setViewportView(btnWellPanel);

        getContentPane().add(jspWell, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 321, 180, 450));

        lblOperatorName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblOperatorName.setPreferredSize(new java.awt.Dimension(176, 62));
        getContentPane().add(lblOperatorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 248, 175, -1));

        jspWellBore.setBorder(null);
        jspWellBore.setPreferredSize(new java.awt.Dimension(1173, 2263));

        wellBorePanel.setBorder(new javax.swing.border.MatteBorder(null));
        wellBorePanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout wellBorePanelLayout = new javax.swing.GroupLayout(wellBorePanel);
        wellBorePanel.setLayout(wellBorePanelLayout);
        wellBorePanelLayout.setHorizontalGroup(
            wellBorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        wellBorePanelLayout.setVerticalGroup(
            wellBorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jspWellBore.setViewportView(wellBorePanel);

        getContentPane().add(jspWellBore, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 245, 210, 530));

        jspProperty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jspProperty.setPreferredSize(new java.awt.Dimension(1173, 2263));

        tblProperty.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblProperty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Properties", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspProperty.setViewportView(tblProperty);

        getContentPane().add(jspProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, 145, 593));

        displayAreaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout displayAreaPanelLayout = new javax.swing.GroupLayout(displayAreaPanel);
        displayAreaPanel.setLayout(displayAreaPanelLayout);
        displayAreaPanelLayout.setHorizontalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        displayAreaPanelLayout.setVerticalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(displayAreaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 182, 710, 593));

        jMenu1.setText("File");

        jmiNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmiNew.setText("New");
        jMenu1.add(jmiNew);

        jmiLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiLoad.setText("Load");
        jmiLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLoadActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLoad);

        jmiSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSave.setText("Save");
        jMenu1.add(jmiSave);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jmiExit.setText("Exit");
        jmiExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiExitMouseClicked(evt);
            }
        });
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        menBarTectTonic.add(jMenu1);

        jMenu2.setText("Edit");
        menBarTectTonic.add(jMenu2);

        jMenu3.setText("Visualize");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Scatter Plot");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Bar Chat");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Line Graph");
        jMenu3.add(jMenuItem7);

        menBarTectTonic.add(jMenu3);

        jMenu4.setText("About");
        menBarTectTonic.add(jMenu4);

        setJMenuBar(menBarTectTonic);

        setSize(new java.awt.Dimension(1305, 846));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmiLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLoadActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("xml file only", ".xml");
        chooser.setFileFilter(fnef);
        int input = chooser.showOpenDialog(this);
        if (input == 0) {

        }
    }//GEN-LAST:event_jmiLoadActionPerformed

    private void combOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combOperatorActionPerformed
        String op = (String) combOperator.getSelectedItem();
        lblOperatorName.setText(op);
        loadwellBtnPanel(op);

    }//GEN-LAST:event_combOperatorActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiExitMouseClicked
    private void loadwellBtnPanel(String op) {
        ArrayList<WitsmlWell> welllist = new ArrayList();
        for (int x = 0; x < wells.size(); x++) {
            if (op.equals(wells.get(x).getOperator())) {
                welllist.add(wells.get(x));

            }
        }
        // load the well panel with well on a button
        int welllistsize = welllist.size();
        btnWellPanel.removeAll();
        //btnWellPanel.setLayout(new GridLayout(welllistsize, 1, 5, 5));
        for (int i = 0; i < welllistsize; i++) {

            JButton btn = new JButton("<html><b>" + welllist.get(i).getName() + "</b></html>");
            btn.setBounds(5, 5, btnWellPanel.getWidth() - 10, 80);
            btn.addActionListener(new ButtonListener(btn, welllist.get(i)));
            btnWellPanel.add(btn);

//            repaint();
            JButton b = (JButton) btnWellPanel.getComponent(0);
            b.doClick();
        }
    }

    class ButtonListener implements ActionListener {

        private final JButton btn;
        private final WitsmlWell well;
        private WitsmlXMLReader xmlreader = new WitsmlXMLReader();

        public ButtonListener(JButton btn, WitsmlWell well) {
            this.btn = btn;
            this.well = well;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
//            System.out.println(btn.getText());
            List<WitsmlWellbore> wellbores = xmlreader.getWellbores(well);
            wellBorePanel.removeAll();
            //wellBorePanel.setLayout(new GridLayout(wellbores.size(), 1, 5, 5));
            for (int i = 0; i < wellbores.size(); i++) {
                WitsmlWellbore wellbore = wellbores.get(i);
                JButton btnWellbore = new JButton("<html><b>Name:  " + wellbore.getName()
                        + "</b><br/> Status:  " + wellbore.getStatus() + "<br> Type:  " + wellbore.getType() + "</br></html>");

                btnWellbore.setBounds(5, ((100 * i) + 5), wellBorePanel.getWidth() - 10, 100);
                wellBorePanel.add(btnWellbore);
                repaint();
                btnWellbore.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {

                        try {
                            logs = xmlreader.getLogs(wellbore);
                            System.out.println("i gas out here ******************************************************");
                            System.out.println("logs : " + logs.toString());
                        } catch (NullPointerException exception) {
                            exception.printStackTrace();
                            System.out.println("exception.printStackTrace() ******************************************************");
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }

                        for (int j = 0; j < logs.size(); j++) {
                            WitsmlLog log = logs.get(j);
                             List<WitsmlLogCurve> curves = log.getCurves();
                            System.out.println(
                                    "name: " + log.getName() + "\n"
                                    + "tvdunit:  " + log.getDescription() + "\n"
                                    + "tvdunit:  " + log.getIndexType() + "\ntvdunit:  " + log.getIndexUnit() + "\n curve : " +log.getCurves() + "\n depth = "+ curves.get(0)+ "\n");

//                            List<WitsmlLogCurve> curves = log.getCurves();
                            WitsmlLogCurve depth = curves.get(0);
                            WitsmlLogCurve measurement = curves.get(j);
                            data.setValue(depth.getName(), measurement.getNValues());
                            JFreeChart piechart = ChartFactory.createPieChart("WitsmlLogCurve", data);
                            displayAreaPanel.add(new ChartFrame(
                                    "Pie Chart using JFreeChart",
                                    piechart));
                        }
                    }
                });
            }
            //WitsmlWellbore wellbore = wellbores.get(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Techtonic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Techtonic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Techtonic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Techtonic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Techtonic().setVisible(true);
            }
        });
    }

    private void loadDisplayScreen() {

        WitsmlXMLReader xmlreader = new WitsmlXMLReader();
        wells = xmlreader.getWells();

        //       wellBtnPanel.setLayout(new GridLayout(wellSize, 1, 5,5));
//      for(WitsmlWell well : wells){
//          opName[] = well.getOperator();
//        }
        for (int i = 0; i < wells.size(); i++) {
            opName.add(new Well(i, wells.get(i).getOperator()));
        }
        Iterator<Well> iterate = opName.iterator();
        while (iterate.hasNext()) {
            arrName.add(iterate.next().getOperator());
        }
        aModel = new DefaultComboBoxModel<>(arrName);
        combOperator.setModel(aModel);

//      displaySheet.append("Number of wells: "+ wellSize+"\n");
//      displaySheet.append("\n"+loadWells);
    }
    private DefaultComboBoxModel<String> aModel;
    private SortedSet<Well> opName = new TreeSet<>();
    List<WitsmlWell> wells;
    private int wellIndex;
    private Vector<String> arrName = new Vector<>();
    DefaultPieDataset data = new DefaultPieDataset();
    List<WitsmlLog> logs = new ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnWellPanel;
    private javax.swing.JComboBox<String> combOperator;
    private javax.swing.JPanel displayAreaPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLoad;
    private javax.swing.JMenuItem jmiNew;
    private javax.swing.JMenuItem jmiSave;
    private javax.swing.JScrollPane jspProperty;
    private javax.swing.JScrollPane jspWell;
    private javax.swing.JScrollPane jspWellBore;
    private javax.swing.JLabel lblOperatorName;
    private javax.swing.JLabel lblOperators;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuBar menBarTectTonic;
    private javax.swing.JPanel operatorPanel;
    private javax.swing.JTable tblProperty;
    private javax.swing.JPanel titleBarPanel;
    private javax.swing.JPanel toolBarPanel;
    private javax.swing.JPanel wellBorePanel;
    // End of variables declaration//GEN-END:variables

}
